services:
  - type: web
    name: hos-planner-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn backend.wsgi:application
    envVars:
      - key: ALLOWED_HOSTS
        value: hos-trip-planner.onrender.com
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DISABLE_COLLECTSTATIC
        value: "1"
      - key: CORS_ALLOWED_ORIGINS
        value: https://frontend-gamma-weld.vercel.app
      - key: MEDIA_ROOT
        value: /media
    disk:
      name: media-disk
      mountPath: /media
      sizeGB: 1
